site_name: 14705 Great Wilow Drive
site_url: http://localhost
copyright: Copyright &copy; 2025 14705 Great Willow Drive
plugins:
  - social:
      cards_layout_options:
        cards_layout: default/invert
        background_image: docs/images/img1.jpg
  # - search
theme:
  name: material
  icon:
    logo: fontawesome/solid/house
  favicon: assets/images/favicon.png
  custom_dir: overrides
  palette:
    primary: teal
    accent: indigo
  features:
    - navigation.tabs
    - navigation.tabs.sticky
extra:
  generator: false
  social:
#    - icon: fontawesome/brands/instagram
#      link: https://instagram.com/14705GreatWillowDrive
#      name: "@14705GreatWillowDrive"
    - icon: material/email
      link: mailto:<contact@14705GreatWillowDrive.com>
      name: contact@14705GreatWillowDrive.com 
    - icon: material/phone
      link: tel:5126938679
      name: (512) 693-8679
markdown_extensions:
  - def_list
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
extra_css:
  - styles/main.css
extra_javascript:
  - js/fslightbox.js
nav:
  - "Application Form": index.md
  - "Contact Us": contact.md
  - "About This Home": about-this-home.md
